name: 'www'

networks:
  gate:
    external: true

services:
  www-tech-breeze-com-mm:
    restart: 'unless-stopped'
    container_name: 'www_tech-breeze-com-mm'
    image: 'breeze-www/tech-breeze-com-mm'
    build: .
    env_file:
      - '.env'
    networks:
      - 'gate'
