name: 'www'

networks:
  gate:
    external: true

services:
  www-tech-breeze-com-mm:
    restart: 'unless-stopped'
    container_name: 'www_tech-breeze-com-mm'
    image: 'www-tech-breeze-com-mm'
    build: .
    environment:
      NODE_ENV: '${NODE_ENV}'
    networks:
      - 'gate'
