name: 'tech-breeze'

services:
  web:
    container_name: 'tech-breeze-web'
    image: 'tech-breeze-web'
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - breeze-net

networks:
  breeze-net:
    name: breeze-net
    driver: bridge