import Footer from '@/components/footer'
import Header from '@/components/header'
import type { Metadata } from 'next'
import '../styles/app.css'
import '../styles/fonts.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`font-neue-june antialiased`}>
        <Header />

        <main className="flex flex-col gap-10">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
